### ISSUE TITLE
[Suggestion] Custom color background for announcements within the icon selected

### ISSUE THREAD

**Issue by MrAstro18** [prplwtf/Nebula#32] opened 2024-05-04 03:48 UTC
For each icons made to use on announcements, it would be useful to set custom color background depending on the case. For example, the warning icon would display a yellow background (or another color of the user's choice)
![image](https://github.com/prplwtf/Nebula/assets/88798450/2d1172fc-097b-4072-a24e-9ba9f9bc6474)

**Comment by prplwtf** [comment] 2024-05-15 12:26
Duplicate of #24

**Closed by prplwtf** 2024-05-15 12:26 UTC
Labels: duplicate, suggestion
