### ISSUE TITLE
Feature Request: Quick jump to admin panel from server

### ISSUE THREAD

**Issue by NorteX-dev** [prplwtf/Nebula#97] opened 2024-11-09 12:36 UTC
Hello. I'm here to request a feature for Nebula that I desperately need and used in my previous theme.

I want a button to **quickly go from client server view to admin server view**.

The admin panel already has such button (to go from admin view to client view):
![image](https://github.com/user-attachments/assets/aebe9b56-43ca-4028-a63d-01353e6ad604)

I'd like, for admins, for a similar button to be shown on the client side.

Alternatively, this button, if viewing a server (like I'm here:) could turn the href to point to the admin server page, instead of just /admin index page.
![image](https://github.com/user-attachments/assets/5b8777ca-7b4e-4f5a-adb5-b3d9ca671198)

There might be a link hidden somewhere that I can't find, in that case please do correct me.

Thanks.

**Comment by prplwtf** [comment] 2024-11-12 15:50
Duplicate of #14 

Planned feature, just hasn't been implemented yet as we've had to prioritize some other issues while working on updates.

**Closed by prplwtf** 2024-11-12 15:50 UTC
